# Generated by Django 6.1.1 on 2026-09-29 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_customerprofile_review_servicerequest_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_id', models.CharField(editable=False, max_length=30, unique=True)),
                ('pickup_company', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('delivery_location', models.CharField(max_length=255)),
                ('item_details', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=30)),
                ('additional_details', models.TextField(blank=True)),
                ('assigned_driver', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('going_to_pickup', 'Going to Pickup'), ('picked_up', 'Picked Up'), ('on_the_way', 'On The Way'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='website.servicerequest')),
            ],
        ),
    ]
