# Generated by Django 6.1.1 on 2026-09-29 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='access_token',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
    ]
