# Generated by Django 6.1.1 on 2026-09-29 11:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_delivery_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='service_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='website.servicerequest'),
        ),
    ]
